### ISSUE TITLE
Map vs Collect / Find vs Detect

### ISSUE THREAD

**Issue by lewispb** [BiggerPockets/patterns#14]
Edd:

> I use collect over map when I’m pulling a field from each of the items, and map when I’m transforming the items, so for instance, names = collection.collect(&:name) and doubled_quantities = collection.map { |item| item.quantity * 2 } (edited) 

Let's also settle on `find` or `.detect`. I prefer `.find`.

**Comment by bockets** [comment]
This is addressed in code climate / rubocop
