### ISSUE TITLE
Avoid using match in routes files

### ISSUE THREAD

**Issue by lewispb** [BiggerPockets/patterns#15]
We should add a Rails guide for when we create routes, that they should always be RESTful.

Kind of related to https://github.com/BiggerPockets/patterns/pull/3

Prompted by discussion with the indomitable @SpiderMasterMind

**Comment by SpiderMasterMind** [comment]
I think `match` is too ambiguous, and using further options to it to change behaviour becomes hard to read. I think we should specifcy which routes should correspond, and/or keep things as resourceful as possible.
