### ISSUE TITLE
Only 1 expectation per "it"

### ISSUE THREAD

**Issue by lewispb** [BiggerPockets/patterns#16]
@SpiderMasterMind and I were discussing the way we test and we feel that we should:

> Prefer multiple short & focused specs, over fewer long specs

**Comment by lewispb** [comment]
We should also avoid using aggregate_failures

**Comment by SpiderMasterMind** [comment]
Single expectation specs can really affect performance, but also make it harder to see where a test has failed, so 'minimising' the number of expectations would get my vote.

`aggregate_failures` seems like an anti-pattern to this?
