### ISSUE TITLE
Let's not let

### ISSUE THREAD

**Issue by kxhitiz** [BiggerPockets/patterns#48]
I'm starting with github issue, so we can have a good conversation here.

This is basically based on this blog post from thoughtbot https://thoughtbot.com/blog/lets-not

Our usage of let is something I've been thinking about for a while. 

The blog post I mentioned basically talks about almost completely getting rid of using let, but what I am proposing it about getting rid of the habit of adding lets on the top of spec. And start scoping it down to given test scenario ie. basically to localize it a bit. Having to scroll up and down specially in big test file just to see the seed factory records being created can be annoying sometimes.

Also, personally I am ok with having some duplication in the spec if it gives more clarity while reading the spec.

I am not all against using let. But I would like us to avoid using it if it is causing following problems in the spec (also from the blog):

- obscures each test by introducing a Mystery Guest. basically hampers the readability of spec.
- It causes Fragile Tests by creating a complicated fixture that is difficult to maintain.
- It causes Slow Tests by creating more data than is necessary in each test.

**Comment by lewispb** [comment]
Thanks so much @kxhitiz for raising this point. I agree with your proposal, especially this line:

>  I am ok with having some duplication in the spec if it gives more clarity while reading the spec

Taken further we could also consider limiting using `subject` and `it_behaves_like`.

**Comment by SpiderMasterMind** [comment]
@kxhitiz Thanks for this one! I'd really like to make a pattern guideline out of this one. Perhaps with some examples of the 'local variables' style of spec over nested contexts, lots of `lets` etc.

Thoughts? @karlentwistle @cernivec @RajaaBoulassouak @johngallagher @sebsogamoso @bockets @bhanubhakta @BPMattBauer

**Comment by johngallagher** [comment]
> @kxhitiz Thanks for this one! I'd really like to make a pattern guideline out of this one. Perhaps with some examples of the 'local variables' style of spec over nested contexts, lots of `lets` etc.
> 
> Thoughts? @karlentwistle @cernivec @RajaaBoulassouak @johngallagher @sebsogamoso @bockets @bhanubhakta @BPMattBauer 

Yes definitely! Totally up for that. Lets really damage our ability to reason about the test.

**Comment by SpiderMasterMind** [comment]
Could definitely start with `Don't use shared examples in their many guises unless there's a really good reason` and `don't use subject`

**Comment by cernivec** [comment]
I'm very much up for not using let at all, the readability outweighs the duplication in this case I think.
